# Generated by Django 3.2.8 on 2021-12-04 01:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('administrador', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Programacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gestion', models.CharField(help_text='Introdusca la gestion', max_length=7)),
                ('grupo', models.IntegerField(help_text='Introdusca el grupo')),
                ('fecha', models.DateTimeField()),
                ('asignatura_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administrador.asignatura')),
                ('estudiante_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administrador.estudiante')),
            ],
            options={
                'ordering': ['-gestion'],
            },
        ),
    ]
