# Generated by Django 3.2.8 on 2021-12-08 00:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programar', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='programacion',
            name='fecha',
        ),
        migrations.AlterField(
            model_name='programacion',
            name='gestion',
            field=models.CharField(help_text='                    ', max_length=7),
        ),
        migrations.AlterField(
            model_name='programacion',
            name='grupo',
            field=models.IntegerField(help_text='                    '),
        ),
    ]
