# Generated by Django 3.2.8 on 2021-12-04 01:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('administrador', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Calificacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parcial_1', models.IntegerField(default=0)),
                ('parcial_2', models.IntegerField(default=0)),
                ('parcial_3', models.IntegerField(default=0)),
                ('practica', models.IntegerField(default=0)),
                ('laboratorio', models.IntegerField(default=0)),
                ('ex_final', models.IntegerField(default=0)),
                ('asignatura_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administrador.asignatura')),
                ('estudiante_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administrador.estudiante')),
            ],
            options={
                'ordering': ['-asignatura_id'],
            },
        ),
    ]
