# Generated by Django 3.2.8 on 2021-12-08 00:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrador', '0002_auto_20211207_1948'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asignatura',
            name='nombre',
            field=models.CharField(help_text='                  ', max_length=30),
        ),
        migrations.AlterField(
            model_name='asignatura',
            name='semestre',
            field=models.IntegerField(help_text='                  '),
        ),
        migrations.AlterField(
            model_name='asignatura',
            name='sigla',
            field=models.CharField(help_text='                  ', max_length=6, unique=True),
        ),
    ]
